version: '2'

services:
    db:
        image: mysql
        command: mysqld --user=root --verbose --skip-sync-frm --innodb_flush_log_at_trx_commit=0 --innodb-support-xa=0 --bind-address=0.0.0.0 --query-cache-type=1
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: ./php7-fpm
        links:
            - db:mysqldb
        volumes:
            - ${APP_PATH}:/var/www/app
            - ./logs/app:/var/www/app/var/logs
            - ./php7-fpm/php-timezone.ini:/usr/local/etc/php/conf.d/docker-php-timezone.ini
#            - ./php7-fpm/ext-xdebug.ini:/usr/local/etc/php/conf.d/ext-xdebug.ini
    nginx:
        build: ./nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
